/**
 * frontend/lib/whiteboard/lessonPresets.ts
 *
 * Pre-configured Synchronized Lesson Beats for Step 4.
 * Integrates natural spoken teaching scripts, neural voice audio URLs,
 * word-level boundary timestamps, and timed DrawCommands with trigger words.
 */

import { WhiteboardLessonBeat } from './types';
import { API_BASE_URL } from '@/lib/api';

export const LESSON_CIRCUIT_SYNCHRONIZED: WhiteboardLessonBeat = {
  id: 'lesson-circuit-sync',
  title: "Ohm's Law Circuit Construction",
  description: 'Synchronized live teaching session explaining DC voltage, resistance, and current flow.',
  speechScript:
    "Let's build a circuit. First, we place a 9-volt DC battery on the left. Next, we connect a 100-ohm resistor on the right. Now, let's draw a wire from the battery to the resistor. Watch how the current flows at 90 milliamps.",
  audioUrl: `${API_BASE_URL}/storage/tts/whiteboard_8e86de1ae80afe69.mp3`,
  durationMs: 18087.5,
  initialViewport: { x: 90, y: 70, scale: 1.0 },
  timingMarks: [
    { word: 'Lets', raw_word: "Let's", offset_ms: 100.0, duration_ms: 549.3 },
    { word: 'build', raw_word: 'build', offset_ms: 649.3, duration_ms: 549.3 },
    { word: 'a', raw_word: 'a', offset_ms: 1198.7, duration_ms: 109.9 },
    { word: 'circuit', raw_word: 'circuit.', offset_ms: 1308.6, duration_ms: 878.9 },
    { word: 'First', raw_word: 'First,', offset_ms: 2137.5, duration_ms: 661.5 },
    { word: 'we', raw_word: 'we', offset_ms: 2799.0, duration_ms: 220.5 },
    { word: 'place', raw_word: 'place', offset_ms: 3019.6, duration_ms: 551.3 },
    { word: 'a', raw_word: 'a', offset_ms: 3570.8, duration_ms: 110.3 },
    { word: '9volt', raw_word: '9-volt', offset_ms: 3681.1, duration_ms: 661.5 },
    { word: 'DC', raw_word: 'DC', offset_ms: 4342.6, duration_ms: 220.5 },
    { word: 'battery', raw_word: 'battery', offset_ms: 4563.1, duration_ms: 771.8 },
    { word: 'on', raw_word: 'on', offset_ms: 5334.9, duration_ms: 220.5 },
    { word: 'the', raw_word: 'the', offset_ms: 5555.4, duration_ms: 330.8 },
    { word: 'left', raw_word: 'left.', offset_ms: 5886.2, duration_ms: 551.3 },
    { word: 'Next', raw_word: 'Next,', offset_ms: 6437.5, duration_ms: 490.9 },
    { word: 'we', raw_word: 'we', offset_ms: 6928.4, duration_ms: 196.3 },
    { word: 'connect', raw_word: 'connect', offset_ms: 7124.7, duration_ms: 687.2 },
    { word: 'a', raw_word: 'a', offset_ms: 7811.9, duration_ms: 98.2 },
    { word: '100ohm', raw_word: '100-ohm', offset_ms: 7910.1, duration_ms: 687.2 },
    { word: 'resistor', raw_word: 'resistor', offset_ms: 8597.3, duration_ms: 785.4 },
    { word: 'on', raw_word: 'on', offset_ms: 9382.6, duration_ms: 196.3 },
    { word: 'the', raw_word: 'the', offset_ms: 9579.0, duration_ms: 294.5 },
    { word: 'right', raw_word: 'right.', offset_ms: 9873.5, duration_ms: 589.0 },
    { word: 'Now', raw_word: 'Now,', offset_ms: 10462.5, duration_ms: 351.1 },
    { word: 'lets', raw_word: "let's", offset_ms: 10813.6, duration_ms: 438.9 },
    { word: 'draw', raw_word: 'draw', offset_ms: 11252.4, duration_ms: 351.1 },
    { word: 'a', raw_word: 'a', offset_ms: 11603.5, duration_ms: 87.8 },
    { word: 'wire', raw_word: 'wire', offset_ms: 11691.3, duration_ms: 351.1 },
    { word: 'from', raw_word: 'from', offset_ms: 12042.4, duration_ms: 351.1 },
    { word: 'the', raw_word: 'the', offset_ms: 12393.5, duration_ms: 263.3 },
    { word: 'battery', raw_word: 'battery', offset_ms: 12656.8, duration_ms: 614.4 },
    { word: 'to', raw_word: 'to', offset_ms: 13271.2, duration_ms: 175.5 },
    { word: 'the', raw_word: 'the', offset_ms: 13446.7, duration_ms: 263.3 },
    { word: 'resistor', raw_word: 'resistor.', offset_ms: 13710.1, duration_ms: 789.9 },
    { word: 'Watch', raw_word: 'Watch', offset_ms: 14500.0, duration_ms: 484.8 },
    { word: 'how', raw_word: 'how', offset_ms: 14984.8, duration_ms: 290.9 },
    { word: 'the', raw_word: 'the', offset_ms: 15275.7, duration_ms: 290.9 },
    { word: 'current', raw_word: 'current', offset_ms: 15566.6, duration_ms: 678.7 },
    { word: 'flows', raw_word: 'flows', offset_ms: 16245.3, duration_ms: 484.8 },
    { word: 'at', raw_word: 'at', offset_ms: 16730.1, duration_ms: 193.9 },
    { word: '90', raw_word: '90', offset_ms: 16924.0, duration_ms: 193.9 },
    { word: 'milliamps', raw_word: 'milliamps.', offset_ms: 17117.9, duration_ms: 969.6 },
  ],
  timedCommands: [
    {
      triggerWord: 'circuit',
      command: {
        op: 'add_text',
        id: 'circuit-title',
        x: 120,
        y: 40,
        text: "Ohm's Law: V = I × R",
        style: { strokeColor: '#F8FAFC', fontSize: 24 },
        linkedStepId: 'step-1-intro',
      },
    },
    {
      triggerWord: 'battery',
      command: {
        op: 'add_shape',
        id: 'battery',
        subtype: 'rectangle',
        x: 120,
        y: 150,
        width: 90,
        height: 60,
        label: '9V DC',
        style: { strokeColor: '#FB7185', fillColor: 'rgba(251, 113, 133, 0.18)', strokeWidth: 3 },
        linkedStepId: 'step-2-source',
      },
    },
    {
      triggerWord: 'left',
      command: {
        op: 'highlight',
        targetId: 'battery',
        durationMs: 1200,
        color: '#FB7185',
      },
    },
    {
      triggerWord: 'resistor',
      command: {
        op: 'add_shape',
        id: 'resistor',
        subtype: 'rectangle',
        x: 380,
        y: 150,
        width: 120,
        height: 60,
        label: '100 Ω',
        style: { strokeColor: '#FBBF24', fillColor: 'rgba(251, 191, 36, 0.18)', strokeWidth: 3 },
        linkedStepId: 'step-3-load',
      },
    },
    {
      triggerWord: 'wire',
      command: {
        op: 'connect_arrow',
        id: 'wire-top',
        from: 'battery.right',
        to: 'resistor.left',
        style: { strokeColor: '#38BDF8', strokeWidth: 3 },
        linkedStepId: 'step-4-wire',
      },
    },
    {
      triggerWord: 'current',
      command: {
        op: 'add_text',
        id: 'current-calc',
        x: 230,
        y: 130,
        text: 'I = 9V / 100Ω = 90 mA',
        style: { strokeColor: '#38BDF8', fontSize: 16 },
        linkedStepId: 'step-5-calc',
      },
    },
    {
      triggerWord: 'flows',
      command: {
        op: 'highlight',
        targetId: 'wire-top',
        durationMs: 1800,
        color: '#38BDF8',
      },
    },
    {
      triggerWord: 'milliamps',
      command: {
        op: 'update_shape',
        targetId: 'resistor',
        label: '100 Ω (Active: 90mA)',
        style: { strokeColor: '#34D399', fillColor: 'rgba(52, 211, 153, 0.18)' },
      },
    },
  ],
};

export const LESSON_BST_SYNCHRONIZED: WhiteboardLessonBeat = {
  id: 'lesson-bst-sync',
  title: 'Binary Search Tree Branching',
  description: 'Synchronized live teaching session demonstrating root comparison and recursive branching.',
  speechScript:
    'Let us examine binary search tree insertion. We begin with our root node 50. When inserting 30, since 30 is less than 50, it branches left. When inserting 70, it branches right.',
  audioUrl: `${API_BASE_URL}/storage/tts/whiteboard_e23fcf82f11cdf59.mp3`,
  durationMs: 15050.0,
  initialViewport: { x: 120, y: 50, scale: 1.0 },
  timingMarks: [
    { word: 'Lets', raw_word: "Let's", offset_ms: 100.0, duration_ms: 465.5 },
    { word: 'examine', raw_word: 'examine', offset_ms: 565.5, duration_ms: 651.6 },
    { word: 'binary', raw_word: 'binary', offset_ms: 1217.1, duration_ms: 558.6 },
    { word: 'search', raw_word: 'search', offset_ms: 1775.7, duration_ms: 558.6 },
    { word: 'tree', raw_word: 'tree', offset_ms: 2334.2, duration_ms: 372.4 },
    { word: 'insertion', raw_word: 'insertion.', offset_ms: 2706.6, duration_ms: 930.9 },
    { word: 'We', raw_word: 'We', offset_ms: 3587.5, duration_ms: 221.0 },
    { word: 'begin', raw_word: 'begin', offset_ms: 3808.5, duration_ms: 552.5 },
    { word: 'with', raw_word: 'with', offset_ms: 4361.0, duration_ms: 442.0 },
    { word: 'our', raw_word: 'our', offset_ms: 4803.0, duration_ms: 331.5 },
    { word: 'root', raw_word: 'root', offset_ms: 5134.5, duration_ms: 442.0 },
    { word: 'node', raw_word: 'node', offset_ms: 5576.5, duration_ms: 442.0 },
    { word: '50', raw_word: '50.', offset_ms: 6018.5, duration_ms: 331.5 },
    { word: 'When', raw_word: 'When', offset_ms: 6350.0, duration_ms: 413.7 },
    { word: 'inserting', raw_word: 'inserting', offset_ms: 6763.7, duration_ms: 930.9 },
    { word: '30', raw_word: '30,', offset_ms: 7694.6, duration_ms: 310.3 },
    { word: 'since', raw_word: 'since', offset_ms: 8004.9, duration_ms: 517.2 },
    { word: '30', raw_word: '30', offset_ms: 8522.1, duration_ms: 206.9 },
    { word: 'is', raw_word: 'is', offset_ms: 8728.9, duration_ms: 206.9 },
    { word: 'less', raw_word: 'less', offset_ms: 8935.8, duration_ms: 413.7 },
    { word: 'than', raw_word: 'than', offset_ms: 9349.5, duration_ms: 413.7 },
    { word: '50', raw_word: '50,', offset_ms: 9763.2, duration_ms: 310.3 },
    { word: 'it', raw_word: 'it', offset_ms: 10073.5, duration_ms: 206.9 },
    { word: 'branches', raw_word: 'branches', offset_ms: 10280.4, duration_ms: 827.5 },
    { word: 'left', raw_word: 'left.', offset_ms: 11107.8, duration_ms: 517.2 },
    { word: 'When', raw_word: 'When', offset_ms: 11625.0, duration_ms: 428.1 },
    { word: 'inserting', raw_word: 'inserting', offset_ms: 12053.1, duration_ms: 963.3 },
    { word: '70', raw_word: '70,', offset_ms: 13016.4, duration_ms: 321.1 },
    { word: 'it', raw_word: 'it', offset_ms: 13337.5, duration_ms: 214.1 },
    { word: 'branches', raw_word: 'branches', offset_ms: 13551.6, duration_ms: 856.2 },
    { word: 'right', raw_word: 'right.', offset_ms: 14407.8, duration_ms: 642.2 },
  ],
  timedCommands: [
    {
      triggerWord: 'insertion',
      command: {
        op: 'add_text',
        id: 'bst-title',
        x: 220,
        y: 20,
        text: 'Binary Search Tree: Insert(30), Insert(70)',
        style: { strokeColor: '#F8FAFC', fontSize: 22 },
        linkedStepId: 'bst-1-intro',
      },
    },
    {
      triggerWord: 'root',
      command: {
        op: 'add_shape',
        id: 'root-50',
        subtype: 'circle',
        x: 320,
        y: 80,
        width: 70,
        height: 70,
        label: '50',
        style: { strokeColor: '#818CF8', fillColor: 'rgba(129, 140, 248, 0.18)', strokeWidth: 3 },
        linkedStepId: 'bst-2-root',
      },
    },
    {
      triggerWord: '50',
      command: {
        op: 'highlight',
        targetId: 'root-50',
        durationMs: 1200,
        color: '#818CF8',
      },
    },
    {
      triggerWord: '30',
      command: {
        op: 'add_shape',
        id: 'node-30',
        subtype: 'circle',
        x: 180,
        y: 220,
        width: 60,
        height: 60,
        label: '30',
        style: { strokeColor: '#34D399', fillColor: 'rgba(52, 211, 153, 0.18)', strokeWidth: 3 },
        linkedStepId: 'bst-3-left',
      },
    },
    {
      triggerWord: 'left',
      command: {
        op: 'connect_arrow',
        id: 'edge-left',
        from: 'root-50.bottom',
        to: 'node-30.top',
        style: { strokeColor: '#94A3B8', strokeWidth: 2.5 },
        linkedStepId: 'bst-3-left',
      },
    },
    {
      triggerWord: 'left',
      command: {
        op: 'highlight',
        targetId: 'node-30',
        durationMs: 1400,
        color: '#34D399',
      },
    },
    {
      triggerWord: '70',
      command: {
        op: 'add_shape',
        id: 'node-70',
        subtype: 'circle',
        x: 460,
        y: 220,
        width: 60,
        height: 60,
        label: '70',
        style: { strokeColor: '#38BDF8', fillColor: 'rgba(56, 189, 248, 0.18)', strokeWidth: 3 },
        linkedStepId: 'bst-4-right',
      },
    },
    {
      triggerWord: 'right',
      command: {
        op: 'connect_arrow',
        id: 'edge-right',
        from: 'root-50.bottom',
        to: 'node-70.top',
        style: { strokeColor: '#94A3B8', strokeWidth: 2.5 },
        linkedStepId: 'bst-4-right',
      },
    },
    {
      triggerWord: 'right',
      command: {
        op: 'highlight',
        targetId: 'node-70',
        durationMs: 1400,
        color: '#38BDF8',
      },
    },
  ],
};