"""
backend/ai/guardrails.py


Guardrails layer for the AI pipeline. Two responsibilities:

    1. Output grounding validation — verify that content generated by the
       planning pipeline (learning phases, quiz items, gap concepts) is
       actually grounded in the source lecture transcript, with a
       retry-with-feedback mechanism when validation fails.
    2. Input relevance validation — detect when a student's live-session
       question is unrelated to the lecture being taught, so it can be
       deflected gracefully instead of being answered as lecture content.

Design notes:
    - Deterministic checks run first (they're free); the LLM judge only
      sees items that pass them, which keeps token usage low.
    - Every failure mode degrades gracefully: the offline pipeline filters
      ungrounded items instead of crashing (mirroring the "never fail on
      the reduce step" philosophy in planning.py), and the live relevance
      check fails open — it answers anyway — when the classifier errors.
    - All LLM access goes through backend/ai/llm.py's chat_completion,
      same as every other AI module.

Requires: openai, pydantic >= 2
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any, Callable, Optional

from pydantic import BaseModel, Field

# Ensure project root is on sys.path for direct-run and package imports.
_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from backend.app.services.ai.llm import chat_completion
from backend.app.schemas.schemas import (
    GapConcept,
    LearningPlan,
    Phase,
    QuizItem,
    TimeRange,
    TranscriptSegment,
)

# ---------------------------------------------------------------------------
# Shared result types
# ---------------------------------------------------------------------------


class GroundingIssue(BaseModel):
    """One grounding problem found in a generated pipeline item.

    The `detail` text is written to be fed back into the generator's prompt
    on a retry attempt, so it always identifies the offending item's content,
    not just its position.
    """
    item_kind: str = Field(..., description="'phase', 'quiz', or 'gap'")
    item_index: int = Field(
        ..., description="Index into the item list (plan.phases / quizzes / gaps)"
    )
    code: str = Field(
        ..., description="Machine-readable reason, e.g. 'timestamp_out_of_range'"
    )
    detail: str = Field(
        ..., description="Human-readable explanation, fed back to the LLM on retry"
    )


class RelevanceVerdict(BaseModel):
    """Whether a live-session question relates to the lecture being taught."""
    is_relevant: bool
    reason: str = ""
    redirect_message: str = Field(
        default="",
        description="Short spoken deflection used when the question is off-topic",
    )


# ---------------------------------------------------------------------------
# Lexical-overlap helpers (cheap first line of defense, no LLM involved)
# ---------------------------------------------------------------------------

_STOPWORDS = frozenset({
    "the", "a", "an", "and", "or", "but", "if", "then", "else", "for", "to",
    "of", "in", "on", "at", "by", "with", "from", "as", "is", "are", "was",
    "were", "be", "been", "being", "it", "its", "this", "that", "these",
    "those", "you", "your", "we", "our", "they", "their", "he", "she", "his",
    "her", "i", "me", "my", "us", "them", "do", "does", "did", "done",
    "have", "has", "had", "not", "no", "so", "such", "what", "which", "who",
    "whom", "when", "where", "why", "how", "can", "could", "will", "would",
    "should", "may", "might", "must", "about", "into", "over", "under",
    "between", "through", "during", "before", "after", "again", "there",
    "here", "all", "any", "both", "each", "few", "more", "most", "other",
    "some", "only", "own", "same", "than", "too", "very", "just", "because",
    "while", "let", "lets", "now", "also", "like", "get", "got", "make",
    "makes", "made", "thing", "things", "something", "anything", "everything",
    "really", "actually", "basically", "going", "know", "think", "want",
    "see", "look", "say", "said", "tell", "told", "question", "answer",
    "explain", "explanation", "mean", "means", "please",
})

# Below this ratio of shared content-word vocabulary, a generated item is
# almost certainly about something the lecture never said. Kept deliberately
# low — paraphrased teaching scripts legitimately introduce new words, so
# this check exists to catch wholesale hallucination, not loose wording.
_MIN_GROUNDING_OVERLAP = 0.2

# A question whose content words overlap the lecture vocabulary at or above
# this ratio is clearly on-topic and skips the LLM classifier entirely.
_RELEVANCE_OVERLAP_THRESHOLD = 0.34


def _tokenize(text: str) -> set[str]:
    """Lowercase word tokens with stopwords and very short tokens removed."""
    return {
        tok
        for tok in re.findall(r"[a-z0-9]+", (text or "").lower())
        if len(tok) > 2 and tok not in _STOPWORDS
    }


def _transcript_vocabulary(transcript: list[TranscriptSegment]) -> set[str]:
    """All content words appearing anywhere in the transcript."""
    vocab: set[str] = set()
    for seg in transcript:
        vocab |= _tokenize(seg.text)
    return vocab


def _lexical_overlap(text: str, vocabulary: set[str]) -> float:
    """Fraction of `text`'s content words that appear in `vocabulary`.

    Returns 1.0 when either side has no usable tokens — there is nothing to
    compare against, so we fail open rather than flag every item.
    """
    tokens = _tokenize(text)
    if not tokens or not vocabulary:
        return 1.0
    return len(tokens & vocabulary) / len(tokens)


def _format_transcript_excerpt(
    transcript: list[TranscriptSegment],
    max_chars: int = 6000,
) -> str:
    """Simple timestamped transcript block for validator prompts.

    Lighter than planning.py's `_format_transcript` (no segment merging) —
    the judge only needs to read what was said, not plan around it.
    """
    lines = [f"[{s.start:.1f}s - {s.end:.1f}s] {s.text}" for s in transcript]
    block = "\n".join(lines)
    if len(block) > max_chars:
        block = block[:max_chars] + "\n... [transcript continues]"
    return block


# ---------------------------------------------------------------------------
# 1a. Deterministic grounding checks
# ---------------------------------------------------------------------------

_TIMESTAMP_TOLERANCE_S = 1.0


def _check_time_range(
    tr: TimeRange,
    item_kind: str,
    item_index: int,
    item_label: str,
    transcript: list[TranscriptSegment],
    transcript_end: float,
) -> list[GroundingIssue]:
    """Validates one cited TimeRange against the actual transcript bounds."""
    issues: list[GroundingIssue] = []

    if tr.end <= tr.start:
        issues.append(GroundingIssue(
            item_kind=item_kind,
            item_index=item_index,
            code="malformed_time_range",
            detail=f"{item_label}: source timestamp start ({tr.start:.1f}s) "
                   f"is not before its end ({tr.end:.1f}s).",
        ))
        return issues  # further checks are meaningless on a broken range

    if tr.end > transcript_end + _TIMESTAMP_TOLERANCE_S:
        issues.append(GroundingIssue(
            item_kind=item_kind,
            item_index=item_index,
            code="timestamp_out_of_range",
            detail=f"{item_label}: source timestamp {tr.start:.1f}s-{tr.end:.1f}s "
                   f"lies outside the transcript (0s-{transcript_end:.1f}s).",
        ))
    elif not any(seg.end >= tr.start and seg.start <= tr.end for seg in transcript):
        issues.append(GroundingIssue(
            item_kind=item_kind,
            item_index=item_index,
            code="timestamp_no_transcript_overlap",
            detail=f"{item_label}: source timestamp {tr.start:.1f}s-{tr.end:.1f}s "
                   f"overlaps no actual transcript segment.",
        ))

    return issues


# ---------------------------------------------------------------------------
# 1b. LLM grounding judge
# ---------------------------------------------------------------------------


class _LLMGroundingVerdict(BaseModel):
    item_index: int
    grounded: bool
    reason: str = ""


class _LLMGroundingResponse(BaseModel):
    verdicts: list[_LLMGroundingVerdict] = Field(default_factory=list)


_GROUNDING_JUDGE_SYSTEM_PROMPT = """\
You are a strict fact-checking judge for an educational pipeline. You are
given a lecture transcript and a list of content items that an AI generated
from it (teaching phases, quiz questions, or gap concepts).

For EACH item, decide whether it is GROUNDED in the transcript:
- grounded = true: the item's claims, concepts, and facts are actually
  discussed or clearly implied by the transcript (and, where a source
  excerpt is cited, the excerpt supports the item). Paraphrasing and
  pedagogical rewording of transcript content still counts as grounded.
- grounded = false: the item invents content that is not in the transcript,
  or its cited excerpt does not support it. Introducing topics the lecture
  never touches is NOT grounded, even if they are topically adjacent.

Respond with a JSON object in this exact shape:
{
  "verdicts": [
    {"item_index": 0, "grounded": true, "reason": "one short sentence"}
  ]
}
Include exactly one verdict per item, using the item indices given.
"""


def _judge_items_with_llm(
    item_kind: str,
    candidates: list[tuple[int, str]],
    transcript: list[TranscriptSegment],
) -> list[GroundingIssue]:
    """One batched LLM call judging candidate items against the transcript.

    `candidates` is a list of (original_index, rendered_item_text) pairs;
    original indices are preserved so verdicts map back to the caller's
    item list even after deterministic checks filtered some items out.
    Fail-open: a failed judge call accepts the items as-is.
    """
    if not candidates:
        return []

    transcript_block = _format_transcript_excerpt(transcript)
    if not transcript_block:
        return []  # nothing to judge against — fail open

    items_block = "\n\n".join(
        f"{item_kind.upper()} {idx}:\n{text}" for idx, text in candidates
    )
    user_prompt = f"TRANSCRIPT:\n{transcript_block}\n\nITEMS TO JUDGE:\n{items_block}"

    try:
        response = chat_completion(
            system_prompt=_GROUNDING_JUDGE_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            temperature=0.1,
            max_tokens=1024,
            response_model=_LLMGroundingResponse,
        )
    except Exception as exc:
        print(f"[guardrails] grounding judge call failed ({exc}); accepting items as-is")
        return []

    valid_indices = {idx for idx, _ in candidates}
    issues: list[GroundingIssue] = []
    for verdict in response.verdicts:
        # Ignore hallucinated indices; items with no verdict are treated as
        # grounded (fail-open — we only remove content on a positive signal).
        if verdict.item_index not in valid_indices:
            continue
        if not verdict.grounded:
            issues.append(GroundingIssue(
                item_kind=item_kind,
                item_index=verdict.item_index,
                code="ungrounded_content",
                detail=f"{item_kind.capitalize()} #{verdict.item_index} is not "
                       f"grounded in the transcript: {verdict.reason}",
            ))
    return issues


# ---------------------------------------------------------------------------
# 1c. Public per-kind validators
# ---------------------------------------------------------------------------


def _phase_judge_text(phase: Phase, transcript: list[TranscriptSegment]) -> str:
    """Renders a phase for the judge, including its cited source excerpt."""
    text = f"title: {phase.title}\nteaching_script: {phase.teaching_script}"
    excerpts: list[str] = []
    for tr in phase.source_timestamps:
        cited = [s.text for s in transcript if s.end >= tr.start and s.start <= tr.end]
        if cited:
            excerpts.append(" ".join(cited[:6]))
    if excerpts:
        text += "\ncited_excerpt: " + "\n".join(excerpts)[:1500]
    return text


def validate_plan(
    plan: LearningPlan,
    transcript: list[TranscriptSegment],
) -> list[GroundingIssue]:
    """Grounding-validation for a generated LearningPlan.

    Deterministic checks (timestamps, empty fields, duplicate orders,
    lexical overlap) run first; surviving phases go to the LLM judge.
    """
    vocab = _transcript_vocabulary(transcript)
    transcript_end = max((s.end for s in transcript), default=0.0)

    issues: list[GroundingIssue] = []
    failed: set[int] = set()
    seen_orders: set[int] = set()

    for idx, phase in enumerate(plan.phases):
        label = f"Phase '{phase.title}' (index {idx})"

        if phase.order in seen_orders:
            issues.append(GroundingIssue(
                item_kind="phase", item_index=idx, code="duplicate_phase_order",
                detail=f"{label}: phase order {phase.order} is used more than once.",
            ))
            failed.add(idx)
        seen_orders.add(phase.order)

        if not phase.title.strip() or not phase.teaching_script.strip():
            issues.append(GroundingIssue(
                item_kind="phase", item_index=idx, code="empty_field",
                detail=f"{label}: title and teaching_script must both be non-empty.",
            ))
            failed.add(idx)
            continue  # no point running the remaining checks on an empty phase

        for tr in phase.source_timestamps:
            tr_issues = _check_time_range(
                tr, "phase", idx, label, transcript, transcript_end
            )
            if tr_issues:
                issues.extend(tr_issues)
                failed.add(idx)

        overlap = _lexical_overlap(f"{phase.title}. {phase.teaching_script}", vocab)
        if overlap < _MIN_GROUNDING_OVERLAP:
            issues.append(GroundingIssue(
                item_kind="phase", item_index=idx, code="ungrounded_content",
                detail=f"{label}: shares almost no vocabulary with the transcript "
                       f"(overlap {overlap:.2f}) — likely not grounded in the lecture.",
            ))
            failed.add(idx)

    candidates = [
        (idx, _phase_judge_text(phase, transcript))
        for idx, phase in enumerate(plan.phases)
        if idx not in failed
    ]
    issues.extend(_judge_items_with_llm("phase", candidates, transcript))
    return issues


def validate_quizzes(
    quizzes: list[QuizItem],
    transcript: list[TranscriptSegment],
) -> list[GroundingIssue]:
    """Grounding-validation for generated quiz items.

    Deterministic checks: non-empty question, exactly 4 unique options,
    correct_answer matching one option character-for-character, timestamp
    sanity, and lexical overlap with the transcript.
    """
    vocab = _transcript_vocabulary(transcript)
    transcript_end = max((s.end for s in transcript), default=0.0)

    issues: list[GroundingIssue] = []
    failed: set[int] = set()

    for idx, quiz in enumerate(quizzes):
        label = f"Quiz question '{quiz.question[:60]}' (index {idx})"

        if not quiz.question.strip():
            issues.append(GroundingIssue(
                item_kind="quiz", item_index=idx, code="empty_field",
                detail=f"{label}: question text must be non-empty.",
            ))
            failed.add(idx)
            continue

        if quiz.correct_answer not in quiz.options:
            issues.append(GroundingIssue(
                item_kind="quiz", item_index=idx, code="answer_not_in_options",
                detail=f"{label}: correct_answer '{quiz.correct_answer[:60]}' is not "
                       f"an exact copy of one of the options.",
            ))
            failed.add(idx)

        if len(quiz.options) != 4 or len(set(quiz.options)) != len(quiz.options):
            issues.append(GroundingIssue(
                item_kind="quiz", item_index=idx, code="bad_options",
                detail=f"{label}: needs exactly 4 distinct options, "
                       f"got {len(quiz.options)}.",
            ))
            failed.add(idx)

        if quiz.source_timestamp:
            tr_issues = _check_time_range(
                quiz.source_timestamp, "quiz", idx, label, transcript, transcript_end
            )
            if tr_issues:
                issues.extend(tr_issues)
                failed.add(idx)

        combined = " ".join([quiz.question, *quiz.options, quiz.correct_answer])
        overlap = _lexical_overlap(combined, vocab)
        if overlap < _MIN_GROUNDING_OVERLAP:
            issues.append(GroundingIssue(
                item_kind="quiz", item_index=idx, code="ungrounded_content",
                detail=f"{label}: shares almost no vocabulary with the transcript "
                       f"(overlap {overlap:.2f}) — likely not grounded in the lecture.",
            ))
            failed.add(idx)

    candidates = [
        (idx, f"question: {q.question}\noptions: {q.options}\n"
              f"correct_answer: {q.correct_answer}")
        for idx, q in enumerate(quizzes)
        if idx not in failed
    ]
    issues.extend(_judge_items_with_llm("quiz", candidates, transcript))
    return issues


def validate_gaps(
    gaps: list[GapConcept],
    transcript: list[TranscriptSegment],
) -> list[GroundingIssue]:
    """Grounding-validation for detected gap concepts.

    A gap must name something the transcript actually mentions — otherwise
    the 'blind spot' itself is a hallucination.
    """
    vocab = _transcript_vocabulary(transcript)
    transcript_end = max((s.end for s in transcript), default=0.0)

    issues: list[GroundingIssue] = []
    failed: set[int] = set()

    for idx, gap in enumerate(gaps):
        label = f"Gap concept '{gap.name}' (index {idx})"

        if not gap.name.strip() or not gap.why_its_a_gap.strip():
            issues.append(GroundingIssue(
                item_kind="gap", item_index=idx, code="empty_field",
                detail=f"{label}: name and why_its_a_gap must both be non-empty.",
            ))
            failed.add(idx)
            continue

        if gap.source_timestamp:
            tr_issues = _check_time_range(
                gap.source_timestamp, "gap", idx, label, transcript, transcript_end
            )
            if tr_issues:
                issues.extend(tr_issues)
                failed.add(idx)

        overlap = _lexical_overlap(f"{gap.name}. {gap.why_its_a_gap}", vocab)
        if overlap < _MIN_GROUNDING_OVERLAP:
            issues.append(GroundingIssue(
                item_kind="gap", item_index=idx, code="ungrounded_content",
                detail=f"{label}: shares almost no vocabulary with the transcript "
                       f"(overlap {overlap:.2f}) — the lecture likely never "
                       f"mentions this concept.",
            ))
            failed.add(idx)

    candidates = [
        (idx, f"name: {g.name}\nwhy_its_a_gap: {g.why_its_a_gap}")
        for idx, g in enumerate(gaps)
        if idx not in failed
    ]
    issues.extend(_judge_items_with_llm("gap", candidates, transcript))
    return issues


def validate_grounding(
    plan: LearningPlan,
    quizzes: list[QuizItem],
    gaps: list[GapConcept],
    transcript: list[TranscriptSegment],
) -> list[GroundingIssue]:
    """Entry point: validate all generated pipeline content at once.

    The pipeline's retry wrapper validates per step instead; this composer
    exists for validating a complete (e.g. previously stored) result.
    """
    return (
        validate_plan(plan, transcript)
        + validate_quizzes(quizzes, transcript)
        + validate_gaps(gaps, transcript)
    )


# ---------------------------------------------------------------------------
# 1d. Retry-with-feedback wrapper
# ---------------------------------------------------------------------------


def _format_issues_for_retry(issues: list[GroundingIssue]) -> str:
    """Renders issues as a bullet list the generator prompt can act on."""
    return "\n".join(f"- [{issue.code}] {issue.detail}" for issue in issues)


def _filter_ungrounded(
    result: Any,
    issues: list[GroundingIssue],
) -> tuple[Any, int]:
    """Removes the flagged items from a generator result.

    Works on LearningPlan (filters .phases) and on plain lists (gaps,
    quizzes). Returns (filtered_result, removed_count).
    """
    bad_indices = {issue.item_index for issue in issues}
    if isinstance(result, LearningPlan):
        kept = [p for idx, p in enumerate(result.phases) if idx not in bad_indices]
        removed = len(result.phases) - len(kept)
        return result.model_copy(update={"phases": kept}), removed
    kept = [item for idx, item in enumerate(result) if idx not in bad_indices]
    return kept, len(result) - len(kept)


def with_grounding_retry(
    generate_fn: Callable[[Optional[str]], Any],
    validate_fn: Callable[[Any], list[GroundingIssue]],
    step_name: str,
    max_attempts: int = 2,
) -> tuple[Any, dict]:
    """Runs a pipeline generation step under grounding validation.

    Flow per attempt: generate -> validate. If issues are found and attempts
    remain, the issues are fed back into the generator via its `feedback`
    argument. After the final attempt, the offending items are filtered out
    and a warning is logged — this function NEVER raises, so a guardrail
    failure can never take the whole pipeline down with it.

    Args:
        generate_fn: Called as generate_fn(feedback); `feedback` is None on
            the first attempt and a rendered issue list afterwards.
        validate_fn: Called with the generated result, returns issues.
        step_name: For log lines, e.g. "plan".
        max_attempts: Total generation attempts (1 = validate once, no retry).

    Returns:
        (result, report) where report = {"attempts": n, "removed": m,
        "issues": [...]} for PipelineResult.validation_report.
    """
    feedback: Optional[str] = None
    result: Any = None
    issues: list[GroundingIssue] = []

    for attempt in range(1, max_attempts + 1):
        result = generate_fn(feedback)
        issues = validate_fn(result)
        if not issues:
            return result, {"attempts": attempt, "removed": 0, "issues": []}
        print(
            f"[guardrails] {step_name}: attempt {attempt} produced "
            f"{len(issues)} grounding issue(s)"
        )
        feedback = _format_issues_for_retry(issues)

    filtered, removed = _filter_ungrounded(result, issues)
    print(
        f"[guardrails] {step_name}: removed {removed} ungrounded item(s) "
        f"after {max_attempts} attempt(s)"
    )
    return filtered, {
        "attempts": max_attempts,
        "removed": removed,
        "issues": [issue.model_dump() for issue in issues],
    }


# ---------------------------------------------------------------------------
# 2. Input relevance validation (live tutoring session)
# ---------------------------------------------------------------------------


class _LLMRelevanceResponse(BaseModel):
    is_relevant: bool
    reason: str = ""
    redirect_message: str = ""


_RELEVANCE_SYSTEM_PROMPT = """\
You are a topic classifier for a live AI tutoring session. A student asked
a question while being taught a lecture. Decide whether the question is
RELEVANT to the lecture or the tutoring session.

RELEVANT means the question is about:
- the lecture's subject matter or any concept it touches (even loosely),
- the current lesson phase being taught,
- the tutoring session itself (e.g. "can you repeat that?", "what phase
  are we on?").

IRRELEVANT means the question is clearly about an unrelated domain the
lecture never touches (e.g. asking a neural-networks lecture for pizza
recommendations, sports scores, or homework in another subject).

If irrelevant, also write a warm, brief redirect_message (1-2 sentences,
spoken aloud by the tutor) that acknowledges the question and steers the
student back to the lecture topic. If relevant, leave redirect_message empty.

Respond with a JSON object in this exact shape:
{
  "is_relevant": true,
  "reason": "one short sentence",
  "redirect_message": ""
}
"""


def check_question_relevance(
    question: str,
    current_phase: Optional[Phase] = None,
    transcript_segments: Optional[list[TranscriptSegment]] = None,
) -> RelevanceVerdict:
    """Classifies whether a live-session question relates to the lecture.

    Two stages:
      1. Fast lexical heuristic — a question whose content words clearly
         overlap the lecture vocabulary is on-topic; no LLM call needed.
      2. LLM fallback classifier for everything else.

    Fail-open: any error in the classifier path treats the question as
    relevant — a broken guardrail must never silence a student.
    """
    clean_question = (question or "").strip()
    if not clean_question:
        return RelevanceVerdict(is_relevant=True, reason="empty question")

    # 1. Fast heuristic pre-check (no LLM call for obviously on-topic input).
    vocab: set[str] = set()
    if current_phase:
        vocab |= _tokenize(current_phase.title)
        vocab |= _tokenize(current_phase.teaching_script)
    for seg in (transcript_segments or [])[:50]:
        vocab |= _tokenize(seg.text)

    q_tokens = _tokenize(clean_question)
    if q_tokens and vocab:
        overlap = len(q_tokens & vocab) / len(q_tokens)
        if overlap >= _RELEVANCE_OVERLAP_THRESHOLD:
            return RelevanceVerdict(
                is_relevant=True,
                reason=f"lexical overlap {overlap:.2f} with lecture content",
            )

    # 2. LLM fallback classifier.
    context_lines: list[str] = []
    if current_phase:
        context_lines.append(f"Current lesson phase: {current_phase.title}")
        context_lines.append(f"What is being taught: {current_phase.teaching_script}")
    excerpt = _format_transcript_excerpt(transcript_segments or [], max_chars=2000)
    if excerpt:
        context_lines.append(f"Lecture transcript excerpt:\n{excerpt}")

    user_prompt = (
        "LECTURE CONTEXT:\n" + "\n\n".join(context_lines)
        + f"\n\nSTUDENT QUESTION:\n\"{clean_question}\""
    )

    try:
        response = chat_completion(
            system_prompt=_RELEVANCE_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            temperature=0.0,
            max_tokens=150,
            response_model=_LLMRelevanceResponse,
        )
    except Exception as exc:
        print(f"[guardrails] relevance check failed ({exc}); treating question as relevant")
        return RelevanceVerdict(
            is_relevant=True,
            reason="relevance classifier unavailable; failing open",
        )

    return RelevanceVerdict(
        is_relevant=response.is_relevant,
        reason=response.reason,
        redirect_message=response.redirect_message,
    )
